# Generated by Django 4.2.6 on 2023-11-15 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activo_fijo', models.CharField(max_length=20)),
                ('año_entrada', models.CharField(max_length=4)),
                ('año_baja', models.CharField(max_length=4, null=True)),
                ('estado', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=12)),
                ('piso', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20)),
                ('passwrd', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Notebook',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activo_fijo', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=30)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.carro')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=20)),
                ('activo_fijo', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.ubicacion')),
            ],
        ),
        migrations.AddField(
            model_name='carro',
            name='ubicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.ubicacion'),
        ),
    ]
