# Generated by Django 4.2.6 on 2023-11-23 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyector',
            fields=[
                ('serial', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('activo_fijo', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.marca')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carritos.ubicacion')),
            ],
        ),
    ]
