# Generated by Django 4.2.6 on 2023-11-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0004_pc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pc',
            name='carro',
        ),
    ]
