# Generated by Django 4.2.6 on 2023-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carritos', '0005_remove_pc_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='notebook',
            name='imagen',
            field=models.ImageField(null=True, upload_to='act_notebook'),
        ),
        migrations.AddField(
            model_name='pc',
            name='imagen',
            field=models.ImageField(null=True, upload_to='act_pc'),
        ),
        migrations.AddField(
            model_name='proyector',
            name='imagen',
            field=models.ImageField(null=True, upload_to='act_proyector'),
        ),
    ]
